In [1]:
from bs4 import BeautifulSoup
import requests
import pandas as pd
from splinter import Browser
import matplotlib.pyplot as plt
import html5lib

In [2]:
# Reading all the 2022 data from CA, FL, and TX
ca_df = pd.read_csv("Data/Excel:CSV/Quick_Statistics_Results_CBHSQ_Data_SAMHSA_California_2022.csv")
ca_df

,State: CA,All Substances,Alcohol Only,Alcohol with secondary drug,Heroin,Other opiates,Cocaine (smoked),Cocaine (other route),Marijuana,Amphetamines,Other stimulants,Tranquilizers,Sedatives,Hallucinogens,PCP,Inhalants,Other/Unknown
0,Total (Number),"115,333","15,612","13,171","16,964","18,972","1,337","1,532","9,787","34,614",156,406,365,93,208,82,"2,034"
1,Total,100.0,13.5,11.4,14.7,16.4,1.2,1.3,8.5,30.0,0.1,0.4,0.3,0.1,0.2,0.1,1.8
2,Gender,All Substances,Alcohol Only,Alcohol with secondary drug,Heroin,Other opiates,Cocaine (smoked),Cocaine (other route),Marijuana,Amphetamines,Other stimulants,Tranquilizers,Sedatives,Hallucinogens,PCP,Inhalants,Other/Unknown
3,Male,62.6,61.3,64.0,67.6,61.0,61.8,71.4,64.3,60.4,64.1,60.8,59.7,64.5,60.1,31.7,63.7
4,Female,37.2,38.4,35.7,32.3,38.9,38.1,28.4,35.5,39.3,35.9,39.2,39.7,35.5,39.9,68.3,36.1
5,Unknown,0.2,0.2,0.3,0.1,0.1,0.1,0.2,0.2,0.3,0.0,0.0,0.5,0.0,0.0,0.0,0.2
6,Total,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0
7,Age,All Substances,Alcohol Only,Alcohol with secondary drug,Heroin,Other opiates,Cocaine (smoked),Cocaine (other route),Marijuana,Amphetamines,Other stimulants,Tranquilizers,Sedatives,Hallucinogens,PCP,Inhalants,Other/Unknown
8,12-17 years,3.9,0.6,1.4,0.0,0.8,0.4,1.4,39.2,0.3,6.4,6.2,9.3,8.6,0.5,4.9,2.8
9,18-20 years,2.1,0.8,1.4,0.5,4.0,0.4,3.9,6.6,1.2,3.2,8.4,8.5,9.7,1.0,9.8,3.4
10,21-25 years,7.7,5.1,7.1,3.9,11.6,1.2,15.5,10.5,7.4,8.3,19.0,15.6,18.3,4.8,11.0,11.8
11,26-30 years,17.5,13.8,17.2,15.5,23.1,4.5,24.7,13.9,18.2,17.3,20.4,21.1,18.3,8.7,22.0,22.2
12,31-35 years,19.9,16.7,19.3,20.0,23.9,7.0,22.8,10.9,22.2,30.1,17.0,17.5,11.8,8.7,15.9,20.2
13,36-40 years,15.2,14.3,16.2,15.0,14.5,7.6,11.1,7.6,18.2,13.5,13.1,11.0,12.9,17.3,19.5,15.8
14,41-45 years,11.0,12.3,12.4,11.7,8.8,6.5,8.0,4.6,12.9,10.9,7.6,6.3,2.2,13.0,8.5,9.4
15,46-50 years,6.9,9.7,8.1,7.5,4.2,12.0,3.9,2.3,7.7,4.5,3.0,3.0,3.2,16.8,4.9,5.2
16,51-55 years,6.4,10.5,7.9,7.6,3.4,20.3,3.5,1.8,6.2,2.6,2.7,2.5,5.4,13.5,0.0,3.7
17,56-60 years,4.9,8.6,5.5,7.4,2.5,20.3,2.5,1.4,3.5,1.3,2.2,3.0,8.6,11.5,1.2,2.4
18,61-65 years,3.1,5.1,2.7,6.2,1.8,14.7,2.0,0.8,1.7,1.3,0.5,1.4,1.1,3.4,2.4,1.9
19,66 years and over,1.6,2.5,0.7,4.6,1.3,5.2,0.9,0.3,0.5,0.6,0.0,0.8,0.0,1.0,0.0,1.1
20,Unknown,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
21,Total,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0
22,Race,All Substances,Alcohol Only,Alcohol with secondary drug,Heroin,Other opiates,Cocaine (smoked),Cocaine (other route),Marijuana,Amphetamines,Other stimulants,Tranquilizers,Sedatives,Hallucinogens,PCP,Inhalants,Other/Unknown
23,White,51.1,52.7,50.7,59.1,63.8,16.2,33.6,33.5,46.2,60.3,55.4,52.9,41.9,15.9,58.5,63.4
24,Black or African-American,11.2,9.8,11.3,10.3,6.0,69.0,23.0,16.5,10.9,10.3,5.4,4.7,25.8,60.6,3.7,6.8
25,American Indian or Alaska Native,1.7,1.4,2.2,1.5,1.8,0.1,0.8,1.3,1.8,0.6,0.2,1.1,2.2,0.5,1.2,1.6
26,Asian or Native Hawaiian or Other Pacific Isla...,2.4,2.4,1.7,1.7,1.9,3.0,3.5,2.3,3.2,7.1,5.4,6.3,6.5,0.0,2.4,2.0
27,Other,27.6,28.1,28.3,22.5,20.5,8.5,33.6,39.7,31.3,17.9,26.6,26.8,17.2,20.2,23.2,20.7
28,Unknown,6.0,5.6,5.8,4.9,6.1,3.1,5.7,6.8,6.6,3.8,6.9,8.2,6.5,2.9,11.0,5.6
29,Total,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0
30,Ethnicity,All Substances,Alcohol Only,Alcohol with secondary drug,Heroin,Other opiates,Cocaine (smoked),Cocaine (other route),Marijuana,Amphetamines,Other stimulants,Tranquilizers,Sedatives,Hallucinogens,PCP,Inhalants,Other/Unknown
31,Hispanic or Latino,42.4,42.3,45.1,34.2,31.9,13.4,48.8,59.4,48.1,40.4,36.7,40.3,30.1,33.2,50.0,29.9
32,Not Hispanic or Latino,57.6,57.7,54.9,65.8,68.1,86.6,51.2,40.6,51.9,59.6,63.3,59.7,69.9,66.8,50.0,70.1
33,Unknown,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
34,Total,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0

In [3]:
# Extract the alcohol column only
ca_alcohol_df = ca_df.iloc[:,[0,2]]
ca_alcohol_df = ca_alcohol_df.rename(columns={"State: CA":'State', 'Alcohol Only':'California'})
ca_alcohol_df

                                                State    California
0                                      Total (Number)        15,612
1                                               Total          13.5
2                                              Gender  Alcohol Only
3                                                Male          61.3
4                                              Female          38.4
5                                             Unknown           0.2
6                                               Total         100.0
7                                                 Age  Alcohol Only
8                                         12-17 years           0.6
9                                         18-20 years           0.8
10                                        21-25 years           5.1
11                                        26-30 years          13.8
12                                        31-35 years          16.7
13                                        36-40 years          14.3
14                                        41-45 years          12.3
15                                        46-50 years           9.7
16                                        51-55 years          10.5
17                                        56-60 years           8.6
18                                        61-65 years           5.1
19                                  66 years and over           2.5
20                                            Unknown           0.0
21                                              Total         100.0
22                                               Race  Alcohol Only
23                                              White          52.7
24                          Black or African-American           9.8
25                   American Indian or Alaska Native           1.4
26  Asian or Native Hawaiian or Other Pacific Isla...           2.4
27                                              Other          28.1
28                                            Unknown           5.6
29                                              Total         100.0
30                                          Ethnicity  Alcohol Only
31                                 Hispanic or Latino          42.3
32                             Not Hispanic or Latino          57.7
33                                            Unknown           0.0
34                                              Total         100.0

In [4]:
# Change unknowns to repective category unknowns
ca_alcohol_df.iloc[5, ca_alcohol_df.columns.get_loc('State')] = "Unknown_gender"
ca_alcohol_df.iloc[20, ca_alcohol_df.columns.get_loc('State')] = "Unknown_age"
ca_alcohol_df.iloc[28, ca_alcohol_df.columns.get_loc('State')] = "Unknown_race"
ca_alcohol_df.iloc[33, ca_alcohol_df.columns.get_loc('State')] = "Unknown_ethnicity"
ca_alcohol_df.iloc[6, ca_alcohol_df.columns.get_loc('State')] = "Total_gender"
ca_alcohol_df.iloc[21, ca_alcohol_df.columns.get_loc('State')] = "Total_age"
ca_alcohol_df.iloc[29, ca_alcohol_df.columns.get_loc('State')] = "Total_race"
ca_alcohol_df.iloc[34, ca_alcohol_df.columns.get_loc('State')] = "Total_ethnicity"

In [5]:
ca_alcohol_df

                                                State    California
0                                      Total (Number)        15,612
1                                               Total          13.5
2                                              Gender  Alcohol Only
3                                                Male          61.3
4                                              Female          38.4
5                                      Unknown_gender           0.2
6                                        Total_gender         100.0
7                                                 Age  Alcohol Only
8                                         12-17 years           0.6
9                                         18-20 years           0.8
10                                        21-25 years           5.1
11                                        26-30 years          13.8
12                                        31-35 years          16.7
13                                        36-40 years          14.3
14                                        41-45 years          12.3
15                                        46-50 years           9.7
16                                        51-55 years          10.5
17                                        56-60 years           8.6
18                                        61-65 years           5.1
19                                  66 years and over           2.5
20                                        Unknown_age           0.0
21                                          Total_age         100.0
22                                               Race  Alcohol Only
23                                              White          52.7
24                          Black or African-American           9.8
25                   American Indian or Alaska Native           1.4
26  Asian or Native Hawaiian or Other Pacific Isla...           2.4
27                                              Other          28.1
28                                       Unknown_race           5.6
29                                         Total_race         100.0
30                                          Ethnicity  Alcohol Only
31                                 Hispanic or Latino          42.3
32                             Not Hispanic or Latino          57.7
33                                  Unknown_ethnicity           0.0
34                                    Total_ethnicity         100.0

In [6]:
# dropping out the category label to keep it clean with indexes information
indexes_to_drop = [2, 7, 22, 30]
ca_alcohol_df = ca_alcohol_df.drop(indexes_to_drop, axis=0)
ca_alcohol_df

                                                State California
0                                      Total (Number)     15,612
1                                               Total       13.5
3                                                Male       61.3
4                                              Female       38.4
5                                      Unknown_gender        0.2
6                                        Total_gender      100.0
8                                         12-17 years        0.6
9                                         18-20 years        0.8
10                                        21-25 years        5.1
11                                        26-30 years       13.8
12                                        31-35 years       16.7
13                                        36-40 years       14.3
14                                        41-45 years       12.3
15                                        46-50 years        9.7
16                                        51-55 years       10.5
17                                        56-60 years        8.6
18                                        61-65 years        5.1
19                                  66 years and over        2.5
20                                        Unknown_age        0.0
21                                          Total_age      100.0
23                                              White       52.7
24                          Black or African-American        9.8
25                   American Indian or Alaska Native        1.4
26  Asian or Native Hawaiian or Other Pacific Isla...        2.4
27                                              Other       28.1
28                                       Unknown_race        5.6
29                                         Total_race      100.0
31                                 Hispanic or Latino       42.3
32                             Not Hispanic or Latino       57.7
33                                  Unknown_ethnicity        0.0
34                                    Total_ethnicity      100.0

In [7]:
# transposing the data to store as JSON later
ca_alcohol_df = ca_alcohol_df.transpose()
ca_alcohol_df

,0,1,3,4,5,6,8,9,10,11,...,24,25,26,27,28,29,31,32,33,34
State,Total (Number),Total,Male,Female,Unknown_gender,Total_gender,12-17 years,18-20 years,21-25 years,26-30 years,...,Black or African-American,American Indian or Alaska Native,Asian or Native Hawaiian or Other Pacific Isla...,Other,Unknown_race,Total_race,Hispanic or Latino,Not Hispanic or Latino,Unknown_ethnicity,Total_ethnicity
California,"15,612",13.5,61.3,38.4,0.2,100.0,0.6,0.8,5.1,13.8,...,9.8,1.4,2.4,28.1,5.6,100.0,42.3,57.7,0.0,100.0

In [8]:
# adjust the rows to headers of the dataframe
ca_alcohol_df.columns = ca_alcohol_df.iloc[0]
ca_alcohol_df = ca_alcohol_df.iloc[1: , :]
ca_alcohol_df

State,Total (Number),Total,Male,Female,Unknown_gender,Total_gender,12-17 years,18-20 years,21-25 years,26-30 years,...,Black or African-American,American Indian or Alaska Native,Asian or Native Hawaiian or Other Pacific Islander,Other,Unknown_race,Total_race,Hispanic or Latino,Not Hispanic or Latino,Unknown_ethnicity,Total_ethnicity
California,"15,612",13.5,61.3,38.4,0.2,100.0,0.6,0.8,5.1,13.8,...,9.8,1.4,2.4,28.1,5.6,100.0,42.3,57.7,0.0,100.0

In [9]:
# read the Florida state data
fl_df = pd.read_csv("Data/Excel:CSV/Quick_Statistics_Results _CBHSQ_Data_SAMHSA_Florida_2022.csv")
fl_df

,State: FL,All Substances,Alcohol Only,Alcohol with secondary drug,Heroin,Other opiates,Cocaine (smoked),Cocaine (other route),Marijuana,Amphetamines,Other stimulants,Tranquilizers,Sedatives,Hallucinogens,PCP,Inhalants,Other/Unknown
0,Total (Number),"38,833","8,303","1,329","2,479","6,258","1,762","1,418","6,375","3,176",463,248,61,131,3,42,"6,785"
1,Total,100.0,21.4,3.4,6.4,16.1,4.5,3.7,16.4,8.2,1.2,0.6,0.2,0.3,0.0,0.1,17.5
2,Gender,All Substances,Alcohol Only,Alcohol with secondary drug,Heroin,Other opiates,Cocaine (smoked),Cocaine (other route),Marijuana,Amphetamines,Other stimulants,Tranquilizers,Sedatives,Hallucinogens,PCP,Inhalants,Other/Unknown
3,Male,61.5,68.1,70.4,58.9,58.6,64.0,66.2,60.5,53.1,59.8,56.5,39.3,63.4,33.3,54.8,59.1
4,Female,38.5,31.9,29.6,41.1,41.4,36.0,33.8,39.5,46.9,40.2,43.5,60.7,36.6,66.7,45.2,40.9
5,Unknown,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,Total,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0
7,Age,All Substances,Alcohol Only,Alcohol with secondary drug,Heroin,Other opiates,Cocaine (smoked),Cocaine (other route),Marijuana,Amphetamines,Other stimulants,Tranquilizers,Sedatives,Hallucinogens,PCP,Inhalants,Other/Unknown
8,12-17 years,16.9,1.2,2.4,0.1,0.3,0.5,0.4,40.9,1.0,19.4,2.4,4.9,6.1,0.0,7.1,53.8
9,18-20 years,2.6,1.0,1.2,0.6,1.5,0.6,1.2,6.7,2.6,2.4,3.6,1.6,5.3,0.0,2.4,3.6
10,21-25 years,6.9,5.1,6.7,5.0,6.5,2.9,4.7,12.4,9.8,7.6,13.7,11.5,12.2,0.0,4.8,4.6
11,26-30 years,12.2,10.2,11.9,17.5,15.7,7.4,12.5,13.0,17.5,14.0,24.6,14.8,21.4,33.3,14.3,7.0
12,31-35 years,15.1,13.7,15.1,22.6,23.7,12.1,16.1,10.1,21.3,17.5,17.3,13.1,19.1,33.3,9.5,8.3
13,36-40 years,13.9,14.5,13.1,21.2,21.2,13.1,14.9,7.1,19.5,14.7,14.1,19.7,19.1,0.0,23.8,7.5
14,41-45 years,9.5,12.0,12.4,13.1,12.6,12.3,10.6,3.7,12.8,8.6,7.3,9.8,6.1,33.3,2.4,4.8
15,46-50 years,7.0,11.2,10.8,7.6,6.9,12.3,9.4,2.2,7.7,7.3,4.4,4.9,3.8,0.0,9.5,3.6
16,51-55 years,5.7,10.5,8.5,5.8,4.9,12.4,10.5,1.4,4.0,2.4,2.4,6.6,3.8,0.0,11.9,2.6
17,56-60 years,5.3,10.7,9.6,3.5,3.4,14.7,9.9,1.4,2.2,3.7,4.8,9.8,2.3,0.0,2.4,1.9
18,61-65 years,3.2,6.7,6.3,2.0,2.1,7.9,6.5,0.7,1.1,1.1,3.6,3.3,0.8,0.0,11.9,1.4
19,66 years and over,1.6,3.3,1.9,1.0,1.1,3.8,3.2,0.3,0.5,1.3,1.6,0.0,0.0,0.0,0.0,0.9
20,Unknown,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
21,Total,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0
22,Race,All Substances,Alcohol Only,Alcohol with secondary drug,Heroin,Other opiates,Cocaine (smoked),Cocaine (other route),Marijuana,Amphetamines,Other stimulants,Tranquilizers,Sedatives,Hallucinogens,PCP,Inhalants,Other/Unknown
23,White,64.6,69.1,64.6,82.1,82.7,46.5,50.1,47.3,80.0,64.8,78.2,67.2,51.1,33.3,69.0,52.5
24,Black or African-American,24.3,19.9,25.1,5.7,8.0,45.9,39.9,39.3,12.3,26.8,8.5,19.7,38.9,66.7,19.0,34.2
25,American Indian or Alaska Native,0.4,0.5,0.6,0.3,0.3,0.5,0.6,0.3,0.4,0.0,0.0,0.0,0.0,0.0,0.0,0.2
26,Asian or Native Hawaiian or Other Pacific Isla...,0.6,0.7,0.4,0.6,0.3,0.5,0.2,0.5,0.5,0.4,0.0,0.0,0.8,0.0,4.8,0.8
27,Other,5.6,5.6,3.5,6.3,4.1,3.0,4.7,7.2,3.7,5.6,7.3,3.3,2.3,0.0,4.8,7.4
28,Unknown,4.6,4.2,5.8,5.0,4.6,3.6,4.5,5.4,3.1,2.4,6.0,9.8,6.9,0.0,2.4,4.8
29,Total,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0
30,Ethnicity,All Substances,Alcohol Only,Alcohol with secondary drug,Heroin,Other opiates,Cocaine (smoked),Cocaine (other route),Marijuana,Amphetamines,Other stimulants,Tranquilizers,Sedatives,Hallucinogens,PCP,Inhalants,Other/Unknown
31,Hispanic or Latino,17.4,18.0,18.1,16.5,13.9,20.1,24.8,21.1,12.2,13.2,21.8,18.0,16.8,0.0,9.5,16.9
32,Not Hispanic or Latino,78.7,78.9,70.4,82.5,81.5,76.3,72.6,72.5,85.8,75.6,72.2,78.7,81.7,100.0,81.0,80.8
33,Unknown,3.9,3.1,11.5,1.0,4.7,3.6,2.6,6.4,2.1,11.2,6.0,3.3,1.5,0.0,9.5,2.2
34,Total,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0

In [10]:
# Extract the alcohol column only
fl_df = fl_df.iloc[:,[0,2]]
fl_df

                                            State: FL  Alcohol Only
0                                      Total (Number)         8,303
1                                               Total          21.4
2                                              Gender  Alcohol Only
3                                                Male          68.1
4                                              Female          31.9
5                                             Unknown           0.0
6                                               Total         100.0
7                                                 Age  Alcohol Only
8                                         12-17 years           1.2
9                                         18-20 years           1.0
10                                        21-25 years           5.1
11                                        26-30 years          10.2
12                                        31-35 years          13.7
13                                        36-40 years          14.5
14                                        41-45 years          12.0
15                                        46-50 years          11.2
16                                        51-55 years          10.5
17                                        56-60 years          10.7
18                                        61-65 years           6.7
19                                  66 years and over           3.3
20                                            Unknown           0.0
21                                              Total         100.0
22                                               Race  Alcohol Only
23                                              White          69.1
24                          Black or African-American          19.9
25                   American Indian or Alaska Native           0.5
26  Asian or Native Hawaiian or Other Pacific Isla...           0.7
27                                              Other           5.6
28                                            Unknown           4.2
29                                              Total         100.0
30                                          Ethnicity  Alcohol Only
31                                 Hispanic or Latino          18.0
32                             Not Hispanic or Latino          78.9
33                                            Unknown           3.1
34                                              Total         100.0

In [11]:
# rename the State column to Florida and Florida column to Alcohol only data
fl_alcohol_df = fl_df.rename(columns={"State: FL":'State', 'Alcohol Only':'Florida'})
fl_alcohol_df

                                                State       Florida
0                                      Total (Number)         8,303
1                                               Total          21.4
2                                              Gender  Alcohol Only
3                                                Male          68.1
4                                              Female          31.9
5                                             Unknown           0.0
6                                               Total         100.0
7                                                 Age  Alcohol Only
8                                         12-17 years           1.2
9                                         18-20 years           1.0
10                                        21-25 years           5.1
11                                        26-30 years          10.2
12                                        31-35 years          13.7
13                                        36-40 years          14.5
14                                        41-45 years          12.0
15                                        46-50 years          11.2
16                                        51-55 years          10.5
17                                        56-60 years          10.7
18                                        61-65 years           6.7
19                                  66 years and over           3.3
20                                            Unknown           0.0
21                                              Total         100.0
22                                               Race  Alcohol Only
23                                              White          69.1
24                          Black or African-American          19.9
25                   American Indian or Alaska Native           0.5
26  Asian or Native Hawaiian or Other Pacific Isla...           0.7
27                                              Other           5.6
28                                            Unknown           4.2
29                                              Total         100.0
30                                          Ethnicity  Alcohol Only
31                                 Hispanic or Latino          18.0
32                             Not Hispanic or Latino          78.9
33                                            Unknown           3.1
34                                              Total         100.0

In [12]:
# Change unknowns to category unknowns
fl_alcohol_df.iloc[5, fl_alcohol_df.columns.get_loc('State')] = "Unknown_gender"
fl_alcohol_df.iloc[20, fl_alcohol_df.columns.get_loc('State')] = "Unknown_age"
fl_alcohol_df.iloc[28, fl_alcohol_df.columns.get_loc('State')] = "Unknown_race"
fl_alcohol_df.iloc[33, fl_alcohol_df.columns.get_loc('State')] = "Unknown_ethnicity"
fl_alcohol_df.iloc[6, fl_alcohol_df.columns.get_loc('State')] = "Total_gender"
fl_alcohol_df.iloc[21, fl_alcohol_df.columns.get_loc('State')] = "Total_age"
fl_alcohol_df.iloc[29, fl_alcohol_df.columns.get_loc('State')] = "Total_race"
fl_alcohol_df.iloc[34, fl_alcohol_df.columns.get_loc('State')] = "Total_ethnicity"
fl_alcohol_df

                                                State       Florida
0                                      Total (Number)         8,303
1                                               Total          21.4
2                                              Gender  Alcohol Only
3                                                Male          68.1
4                                              Female          31.9
5                                      Unknown_gender           0.0
6                                        Total_gender         100.0
7                                                 Age  Alcohol Only
8                                         12-17 years           1.2
9                                         18-20 years           1.0
10                                        21-25 years           5.1
11                                        26-30 years          10.2
12                                        31-35 years          13.7
13                                        36-40 years          14.5
14                                        41-45 years          12.0
15                                        46-50 years          11.2
16                                        51-55 years          10.5
17                                        56-60 years          10.7
18                                        61-65 years           6.7
19                                  66 years and over           3.3
20                                        Unknown_age           0.0
21                                          Total_age         100.0
22                                               Race  Alcohol Only
23                                              White          69.1
24                          Black or African-American          19.9
25                   American Indian or Alaska Native           0.5
26  Asian or Native Hawaiian or Other Pacific Isla...           0.7
27                                              Other           5.6
28                                       Unknown_race           4.2
29                                         Total_race         100.0
30                                          Ethnicity  Alcohol Only
31                                 Hispanic or Latino          18.0
32                             Not Hispanic or Latino          78.9
33                                  Unknown_ethnicity           3.1
34                                    Total_ethnicity         100.0

In [13]:
# dropping out the category label to keep it clean with indexes information
indexes_to_drop = [2, 7, 22, 30]
fl_alcohol_df = fl_alcohol_df.drop(indexes_to_drop, axis=0)
fl_alcohol_df

                                                State Florida
0                                      Total (Number)   8,303
1                                               Total    21.4
3                                                Male    68.1
4                                              Female    31.9
5                                      Unknown_gender     0.0
6                                        Total_gender   100.0
8                                         12-17 years     1.2
9                                         18-20 years     1.0
10                                        21-25 years     5.1
11                                        26-30 years    10.2
12                                        31-35 years    13.7
13                                        36-40 years    14.5
14                                        41-45 years    12.0
15                                        46-50 years    11.2
16                                        51-55 years    10.5
17                                        56-60 years    10.7
18                                        61-65 years     6.7
19                                  66 years and over     3.3
20                                        Unknown_age     0.0
21                                          Total_age   100.0
23                                              White    69.1
24                          Black or African-American    19.9
25                   American Indian or Alaska Native     0.5
26  Asian or Native Hawaiian or Other Pacific Isla...     0.7
27                                              Other     5.6
28                                       Unknown_race     4.2
29                                         Total_race   100.0
31                                 Hispanic or Latino    18.0
32                             Not Hispanic or Latino    78.9
33                                  Unknown_ethnicity     3.1
34                                    Total_ethnicity   100.0

In [14]:
# transpose the data to make JSON later
fl_alcohol_df = fl_alcohol_df.transpose()
fl_alcohol_df

,0,1,3,4,5,6,8,9,10,11,...,24,25,26,27,28,29,31,32,33,34
State,Total (Number),Total,Male,Female,Unknown_gender,Total_gender,12-17 years,18-20 years,21-25 years,26-30 years,...,Black or African-American,American Indian or Alaska Native,Asian or Native Hawaiian or Other Pacific Isla...,Other,Unknown_race,Total_race,Hispanic or Latino,Not Hispanic or Latino,Unknown_ethnicity,Total_ethnicity
Florida,"8,303",21.4,68.1,31.9,0.0,100.0,1.2,1.0,5.1,10.2,...,19.9,0.5,0.7,5.6,4.2,100.0,18.0,78.9,3.1,100.0

In [15]:
# adjust the rows to make header
fl_alcohol_df.columns = fl_alcohol_df.iloc[0]
fl_alcohol_df = fl_alcohol_df.iloc[1: , :]
fl_alcohol_df

State,Total (Number),Total,Male,Female,Unknown_gender,Total_gender,12-17 years,18-20 years,21-25 years,26-30 years,...,Black or African-American,American Indian or Alaska Native,Asian or Native Hawaiian or Other Pacific Islander,Other,Unknown_race,Total_race,Hispanic or Latino,Not Hispanic or Latino,Unknown_ethnicity,Total_ethnicity
Florida,"8,303",21.4,68.1,31.9,0.0,100.0,1.2,1.0,5.1,10.2,...,19.9,0.5,0.7,5.6,4.2,100.0,18.0,78.9,3.1,100.0

In [16]:
# Read the Texas state data
tx_df = pd.read_csv("Data/Excel:CSV/Quick_Statistics_Results_CBHSQ_Data_SAMHSA_Texas_2022.csv")
tx_df

,State: TX,All Substances,Alcohol Only,Alcohol with secondary drug,Heroin,Other opiates,Cocaine (smoked),Cocaine (other route),Marijuana,Amphetamines,Other stimulants,Tranquilizers,Sedatives,Hallucinogens,PCP,Inhalants,Other/Unknown
0,Total (Number),"31,422","5,283","3,452","4,965","2,361","1,052","1,020","5,324","6,687",8,473,29,41,211,12,504
1,Total,100.0,16.8,11.0,15.8,7.5,3.3,3.2,16.9,21.3,0.0,1.5,0.1,0.1,0.7,0.0,1.6
2,Gender,All Substances,Alcohol Only,Alcohol with secondary drug,Heroin,Other opiates,Cocaine (smoked),Cocaine (other route),Marijuana,Amphetamines,Other stimulants,Tranquilizers,Sedatives,Hallucinogens,PCP,Inhalants,Other/Unknown
3,Male,62.8,68.7,63.9,66.5,56.8,59.1,63.5,70.6,51.7,75.0,55.2,48.3,70.7,59.7,50.0,67.1
4,Female,37.2,31.3,36.1,33.5,43.2,40.9,36.5,29.4,48.3,25.0,44.8,51.7,29.3,40.3,50.0,32.9
5,Unknown,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,Total,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0
7,Age,All Substances,Alcohol Only,Alcohol with secondary drug,Heroin,Other opiates,Cocaine (smoked),Cocaine (other route),Marijuana,Amphetamines,Other stimulants,Tranquilizers,Sedatives,Hallucinogens,PCP,Inhalants,Other/Unknown
8,12-17 years,7.1,0.5,1.0,0.0,2.2,0.4,2.4,37.4,0.3,0.0,11.2,27.6,9.8,0.0,8.3,3.0
9,18-20 years,2.0,0.5,1.4,0.5,4.3,0.6,2.7,4.9,1.2,0.0,4.9,0.0,4.9,0.5,0.0,2.8
10,21-25 years,9.4,5.3,8.8,6.7,11.3,2.4,10.8,16.5,8.8,25.0,15.2,17.2,9.8,3.3,0.0,13.5
11,26-30 years,16.4,12.6,16.1,21.0,19.7,6.3,17.6,14.3,18.5,0.0,17.1,17.2,24.4,4.7,33.3,16.7
12,31-35 years,18.3,15.4,19.3,23.9,19.5,11.3,20.8,11.1,21.8,12.5,23.3,3.4,22.0,19.4,16.7,18.3
13,36-40 years,15.6,16.8,17.5,19.3,17.0,10.0,15.0,7.0,18.1,25.0,11.6,17.2,14.6,31.3,16.7,16.9
14,41-45 years,11.3,13.6,12.6,12.5,10.3,12.5,13.3,4.2,13.5,25.0,6.1,3.4,9.8,25.1,0.0,11.7
15,46-50 years,7.4,11.3,8.2,6.7,6.5,11.2,7.9,2.2,8.2,0.0,5.1,0.0,2.4,10.0,25.0,6.0
16,51-55 years,5.7,10.6,7.1,4.2,4.0,16.0,4.5,1.1,5.3,12.5,2.5,0.0,2.4,4.3,0.0,5.0
17,56-60 years,4.0,7.5,4.6,3.2,3.0,18.0,3.3,0.7,2.7,0.0,1.9,13.8,0.0,1.4,0.0,3.0
18,61-65 years,2.1,4.4,2.4,1.6,1.7,8.7,1.1,0.5,1.1,0.0,1.1,0.0,0.0,0.0,0.0,2.6
19,66 years and over,0.7,1.4,0.9,0.4,0.6,2.9,0.5,0.2,0.3,0.0,0.0,0.0,0.0,0.0,0.0,0.8
20,Unknown,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
21,Total,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0
22,Race,All Substances,Alcohol Only,Alcohol with secondary drug,Heroin,Other opiates,Cocaine (smoked),Cocaine (other route),Marijuana,Amphetamines,Other stimulants,Tranquilizers,Sedatives,Hallucinogens,PCP,Inhalants,Other/Unknown
23,White,80.7,85.3,81.1,92.6,86.1,43.3,70.0,65.1,88.4,75.0,89.4,93.1,56.1,9.0,66.7,71.0
24,Black or African-American,16.7,11.9,16.2,5.2,10.8,54.8,27.2,32.6,8.6,25.0,8.9,3.4,41.5,89.6,25.0,26.6
25,American Indian or Alaska Native,0.6,0.8,0.6,0.5,0.7,0.1,0.8,0.5,0.7,0.0,0.0,0.0,0.0,0.0,0.0,1.0
26,Asian or Native Hawaiian or Other Pacific Isla...,0.7,0.8,0.4,0.6,1.0,0.5,1.2,0.6,0.6,0.0,0.6,0.0,0.0,0.5,0.0,0.6
27,Other,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
28,Unknown,1.3,1.3,1.7,1.1,1.4,1.4,0.9,1.1,1.6,0.0,1.1,3.4,2.4,0.9,8.3,0.8
29,Total,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0
30,Ethnicity,All Substances,Alcohol Only,Alcohol with secondary drug,Heroin,Other opiates,Cocaine (smoked),Cocaine (other route),Marijuana,Amphetamines,Other stimulants,Tranquilizers,Sedatives,Hallucinogens,PCP,Inhalants,Other/Unknown
31,Hispanic or Latino,32.6,31.6,32.5,37.3,26.7,20.8,47.0,38.7,27.9,37.5,35.9,27.6,17.1,4.3,16.7,28.2
32,Not Hispanic or Latino,67.1,67.9,67.1,62.7,73.1,78.9,53.0,61.1,71.5,62.5,63.8,72.4,82.9,95.7,83.3,71.6
33,Unknown,0.3,0.5,0.4,0.1,0.2,0.3,0.0,0.2,0.6,0.0,0.2,0.0,0.0,0.0,0.0,0.2
34,Total,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0

In [17]:
# Extract the alcohol only column
tx_df = tx_df.iloc[:,[0,2]]
tx_df

                                            State: TX  Alcohol Only
0                                      Total (Number)         5,283
1                                               Total          16.8
2                                              Gender  Alcohol Only
3                                                Male          68.7
4                                              Female          31.3
5                                             Unknown           0.0
6                                               Total         100.0
7                                                 Age  Alcohol Only
8                                         12-17 years           0.5
9                                         18-20 years           0.5
10                                        21-25 years           5.3
11                                        26-30 years          12.6
12                                        31-35 years          15.4
13                                        36-40 years          16.8
14                                        41-45 years          13.6
15                                        46-50 years          11.3
16                                        51-55 years          10.6
17                                        56-60 years           7.5
18                                        61-65 years           4.4
19                                  66 years and over           1.4
20                                            Unknown           0.0
21                                              Total         100.0
22                                               Race  Alcohol Only
23                                              White          85.3
24                          Black or African-American          11.9
25                   American Indian or Alaska Native           0.8
26  Asian or Native Hawaiian or Other Pacific Isla...           0.8
27                                              Other           0.0
28                                            Unknown           1.3
29                                              Total         100.0
30                                          Ethnicity  Alcohol Only
31                                 Hispanic or Latino          31.6
32                             Not Hispanic or Latino          67.9
33                                            Unknown           0.5
34                                              Total         100.0

In [18]:
# Rename the State column to Texas, Alochol only column to Texas
tx_alcohol_df = tx_df.rename(columns={"State: TX":'State', 'Alcohol Only':'Texas'})
tx_alcohol_df

                                                State         Texas
0                                      Total (Number)         5,283
1                                               Total          16.8
2                                              Gender  Alcohol Only
3                                                Male          68.7
4                                              Female          31.3
5                                             Unknown           0.0
6                                               Total         100.0
7                                                 Age  Alcohol Only
8                                         12-17 years           0.5
9                                         18-20 years           0.5
10                                        21-25 years           5.3
11                                        26-30 years          12.6
12                                        31-35 years          15.4
13                                        36-40 years          16.8
14                                        41-45 years          13.6
15                                        46-50 years          11.3
16                                        51-55 years          10.6
17                                        56-60 years           7.5
18                                        61-65 years           4.4
19                                  66 years and over           1.4
20                                            Unknown           0.0
21                                              Total         100.0
22                                               Race  Alcohol Only
23                                              White          85.3
24                          Black or African-American          11.9
25                   American Indian or Alaska Native           0.8
26  Asian or Native Hawaiian or Other Pacific Isla...           0.8
27                                              Other           0.0
28                                            Unknown           1.3
29                                              Total         100.0
30                                          Ethnicity  Alcohol Only
31                                 Hispanic or Latino          31.6
32                             Not Hispanic or Latino          67.9
33                                            Unknown           0.5
34                                              Total         100.0

In [19]:
# Change unknowns to category unknowns
tx_alcohol_df.iloc[5, tx_alcohol_df.columns.get_loc('State')] = "Unknown_gender"
tx_alcohol_df.iloc[20, tx_alcohol_df.columns.get_loc('State')] = "Unknown_age"
tx_alcohol_df.iloc[28, tx_alcohol_df.columns.get_loc('State')] = "Unknown_race"
tx_alcohol_df.iloc[33, tx_alcohol_df.columns.get_loc('State')] = "Unknown_ethnicity"
tx_alcohol_df.iloc[6, tx_alcohol_df.columns.get_loc('State')] = "Total_gender"
tx_alcohol_df.iloc[21, tx_alcohol_df.columns.get_loc('State')] = "Total_age"
tx_alcohol_df.iloc[29, tx_alcohol_df.columns.get_loc('State')] = "Total_race"
tx_alcohol_df.iloc[34, tx_alcohol_df.columns.get_loc('State')] = "Total_ethnicity"
tx_alcohol_df

                                                State         Texas
0                                      Total (Number)         5,283
1                                               Total          16.8
2                                              Gender  Alcohol Only
3                                                Male          68.7
4                                              Female          31.3
5                                      Unknown_gender           0.0
6                                        Total_gender         100.0
7                                                 Age  Alcohol Only
8                                         12-17 years           0.5
9                                         18-20 years           0.5
10                                        21-25 years           5.3
11                                        26-30 years          12.6
12                                        31-35 years          15.4
13                                        36-40 years          16.8
14                                        41-45 years          13.6
15                                        46-50 years          11.3
16                                        51-55 years          10.6
17                                        56-60 years           7.5
18                                        61-65 years           4.4
19                                  66 years and over           1.4
20                                        Unknown_age           0.0
21                                          Total_age         100.0
22                                               Race  Alcohol Only
23                                              White          85.3
24                          Black or African-American          11.9
25                   American Indian or Alaska Native           0.8
26  Asian or Native Hawaiian or Other Pacific Isla...           0.8
27                                              Other           0.0
28                                       Unknown_race           1.3
29                                         Total_race         100.0
30                                          Ethnicity  Alcohol Only
31                                 Hispanic or Latino          31.6
32                             Not Hispanic or Latino          67.9
33                                  Unknown_ethnicity           0.5
34                                    Total_ethnicity         100.0

In [20]:
# dropping out the category label to keep it clean with indexes information
indexes_to_drop = [2, 7, 22, 30]
tx_alcohol_df = tx_alcohol_df.drop(indexes_to_drop, axis=0)
tx_alcohol_df

                                                State  Texas
0                                      Total (Number)  5,283
1                                               Total   16.8
3                                                Male   68.7
4                                              Female   31.3
5                                      Unknown_gender    0.0
6                                        Total_gender  100.0
8                                         12-17 years    0.5
9                                         18-20 years    0.5
10                                        21-25 years    5.3
11                                        26-30 years   12.6
12                                        31-35 years   15.4
13                                        36-40 years   16.8
14                                        41-45 years   13.6
15                                        46-50 years   11.3
16                                        51-55 years   10.6
17                                        56-60 years    7.5
18                                        61-65 years    4.4
19                                  66 years and over    1.4
20                                        Unknown_age    0.0
21                                          Total_age  100.0
23                                              White   85.3
24                          Black or African-American   11.9
25                   American Indian or Alaska Native    0.8
26  Asian or Native Hawaiian or Other Pacific Isla...    0.8
27                                              Other    0.0
28                                       Unknown_race    1.3
29                                         Total_race  100.0
31                                 Hispanic or Latino   31.6
32                             Not Hispanic or Latino   67.9
33                                  Unknown_ethnicity    0.5
34                                    Total_ethnicity  100.0

In [21]:
# transpose the data to prepare for JSON later
tx_alcohol_df = tx_alcohol_df.transpose()
tx_alcohol_df

,0,1,3,4,5,6,8,9,10,11,...,24,25,26,27,28,29,31,32,33,34
State,Total (Number),Total,Male,Female,Unknown_gender,Total_gender,12-17 years,18-20 years,21-25 years,26-30 years,...,Black or African-American,American Indian or Alaska Native,Asian or Native Hawaiian or Other Pacific Isla...,Other,Unknown_race,Total_race,Hispanic or Latino,Not Hispanic or Latino,Unknown_ethnicity,Total_ethnicity
Texas,"5,283",16.8,68.7,31.3,0.0,100.0,0.5,0.5,5.3,12.6,...,11.9,0.8,0.8,0.0,1.3,100.0,31.6,67.9,0.5,100.0

In [22]:
# Adjust the rows to become header
tx_alcohol_df.columns = tx_alcohol_df.iloc[0]
tx_alcohol_df = tx_alcohol_df.iloc[1: , :]
tx_alcohol_df

State,Total (Number),Total,Male,Female,Unknown_gender,Total_gender,12-17 years,18-20 years,21-25 years,26-30 years,...,Black or African-American,American Indian or Alaska Native,Asian or Native Hawaiian or Other Pacific Islander,Other,Unknown_race,Total_race,Hispanic or Latino,Not Hispanic or Latino,Unknown_ethnicity,Total_ethnicity
Texas,"5,283",16.8,68.7,31.3,0.0,100.0,0.5,0.5,5.3,12.6,...,11.9,0.8,0.8,0.0,1.3,100.0,31.6,67.9,0.5,100.0

In [23]:
# concatenate the three dataframes and reset the index
merged_df = pd.concat([ca_alcohol_df, fl_alcohol_df, tx_alcohol_df])
merged_df.reset_index(inplace=True)

In [24]:
# reanme columns
merged_df = merged_df.rename(columns={"index":"State"})

In [25]:
# Convert dataframe into json object
json_data = merged_df.to_json("Data/JSON_Files/samhsa_alcohol.json", orient="records")
  
# Print json object
print(json_data)

None